# flake8: noqa
# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.7
  - scikit-learn=0.24.1
  - pandas=1.1.5
  - matplotlib=3.3.3
  - pip:
    - azureml-sdk==1.27.0
    - dotnetcore2==2.1.*
channels:
  - conda-forge
